language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
after_success:
  - npm run report-coverage
before_deploy:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
