export const AUTHENTICATION_CONSTANTS = {
  LOGIN_SUCCESS: 'AUTHENTICATION_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'AUTHENTICATION_LOGIN_FAILURE',
  LOGOUT: 'AUTHENTICATION_LOGOUT'
};

export const CALENDAR_CONSTANTS = {
  MONTH_LOADED: 'MONTH_LOADED',
  MONTH_CHANGED: 'MONTH_CHANGED'
};

export const WORK_LOG_CONSTANTS = {
  LOAD_WORK_LOGS: 'LOAD_WORK_LOGS',
  WORK_LOGS_LOADED: 'WORK_LOGS_LOADED',
  SAVE_WORK_LOG: 'SAVE_WORK_LOG',
  LOAD_TAGS: 'LOAD_TAGS',
  TAGS_LOADED: 'TAGS_LOADED',
  UPDATE_WORK_LOG: 'UPDATE_WORK_LOG',
  WORK_LOG_UPDATED: 'WORK_LOG_UPDATED',
  REMOVE_WORK_LOG: 'REMOVE_WORK_LOG',
  WORK_LOG_REMOVED: 'WORK_LOG_REMOVED',
  BULK_EDIT_REQUEST: 'BULK_EDIT_REQUEST',
  BULK_EDIT_DONE: 'BULK_EDIT_DONE',
};

export const REGISTRATION_CONSTANTS = {
  WORK_LOG_CHANGED: 'WORK_LOG_CHANGED',
  WORK_LOG_SAVED: 'WORK_LOG_SAVED',
  LOAD_PRESETS: 'LOAD_PRESETS',
  PRESETS_LOADED: 'PRESETS_LOADED'
};

export const LEFT_MENU_CONSTANTS = {
  VISIBILITY_CHANGE: 'VISIBILITY_CHANGE'
};

export const NOTIFICATIONS_CONSTANTS = {
  NOTIFICATION_CREATED: 'NOTIFICATION_CREATED',
  NOTIFICATION_DISMISSED: 'NOTIFICATION_DISMISSED'
};

export const ADMIN_CONSTANTS = {
  LOAD_SERVICE_ACCOUNTS: 'LOAD_SERVICE_ACCOUNTS',
  SERVICE_ACCOUNTS_LOADED: 'SERVICE_ACCOUNTS_LOADED',
  DELETE_SERVICE_ACCOUNT: 'DELETE_SERVICE_ACCOUNT',
  SERVICE_ACCOUNT_DELETED: 'SERVICE_ACCOUNT_DELETED',
  LOAD_AUTHORIZED_USERS: 'LOAD_AUTHORIZED_USERS',
  AUTHORIZED_USERS_LOADED: 'AUTHORIZED_USERS_LOADED'
};
