
export const AUTHENTICATION_CONSTANTS = {
  LOGIN_REQUEST: 'AUTHENTICATION_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'AUTHENTICATION_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'AUTHENTICATION_LOGIN_FAILURE',
  LOGOUT: 'AUTHENTICATION_LOGOUT'
};

export const CALENDAR_CONSTANTS = {
  MONTH_LOADED: 'MONTH_LOADED',
  MONTH_CHANGED: 'MONTH_CHANGED'
};

export const WORK_LOG_CONSTANTS = {
  WORK_LOGS_LOADED: 'WORK_LOGS_LOADED',
  TAGS_LOADED: 'TAGS_LOADED',
  WORK_LOG_UPDATED: 'WORK_LOG_UPDATED',
  WORK_LOG_REMOVED: 'WORK_LOG_REMOVED'
};

export const REGISTRATION_CONSTANTS = {
  WORK_LOG_CHANGED: 'WORK_LOG_CHANGED',
  WORK_LOG_SAVED: 'WORK_LOG_SAVED'
};

export const REPORTING_CONSTANTS = {
  TAGS_SELECTION_CHANGED: 'TAGS_SELECTION_CHANGED',
  EMPLOYEES_SELECTION_CHANGED: 'EMPLOYEES_SELECTION_CHANGED',
  REPORT_TYPE_CHANGED: 'REPORT_TYPE_CHANGED'
};

export const LEFT_MENU_CONSTANTS = {
  VISIBILITY_CHANGE: 'VISIBILITY_CHANGE'
};