# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    name: "Build Open Trapp UI"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build
      - run: npm test
      #- name: Coveralls
      #  uses: coverallsapp/github-action@master
      #  with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v1
        name: Upload build as artifact
        if: always()
        with:
          name: open-trapp-ui-dist
          path: ./build
  deploy-on-github-pages:
    name: "Deploy app to GitHub Pages from master branch source code"
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: open-trapp-ui-dist
          path: ./build
      - name: Deploy app as GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.0-6
        if: ${{ github.event_name != 'pull_request' && always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "./build"
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          force_orphan: true
          keep_files: false
  deploy-on-cloudfront:
    name: "Deploy app to CloudFront from master branch source code"
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: open-trapp-ui-dist
          path: ./build
      - name: "Setting AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: "Deploy app to CloudFront with S3 origin from master branch source code"
        uses: lbertenasco/s3-deploy@v1
        if: ${{ github.event_name != 'pull_request' && always() }}
        with:
          folder: ./build
          bucket: ${{ secrets.S3_BUCKET }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: / *
